---
kind: Namespace
apiVersion: v1
metadata:
  name: APP_NAME
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: SERVICE_NAME
  namespace: APP_NAME
  labels:
    account: SERVICE_NAME
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: SERVICE_NAME
  namespace: APP_NAME
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","post","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","post","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: SERVICE_NAME
  namespace: APP_NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: APP_NAME
subjects:
- kind: ServiceAccount
  name: SERVICE_NAME
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: SERVICE_NAME-BRANCH_NAME
  namespace: APP_NAME
  labels:
    app: SERVICE_NAME
    version: BRANCH_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
        version: BRANCH_NAME
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: SERVICE_NAME
      containers:
        - name: SERVICE_NAME-BRANCH_NAME
          image: DOCKER_USER/SERVICE_NAME:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 90
            httpGet:
              path: LIVENESS_URL
              port: SERVICE_PORT
          readinessProbe:
            httpGet:
              path: READINESS_URL
              port: SERVICE_PORT
          ports:
            - name: https-front
              containerPort: 8081
            - name: https-user
              containerPort: SERVICE_PORT
            - name: https-med
              containerPort: 8083
            - name: mysql
              containerPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: SERVICE_NAME
  namespace: APP_NAME
spec:
  ports:
    - name: https
      protocol: TCP
      port: SERVICE_PORT
      targetPort: SERVICE_PORT
  selector:
    app: SERVICE_NAME
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: SERVICE_NAME-BRANCH_NAME
  namespace: default
spec:
  hosts:
  - "SERVICE_NAME.APP_NAME.svc.cluster.local"
  gateways:
  - "main-gateway"
  tcp:
  - timeout: 60s
    route:
    - destination:
        host: SERVICE_NAME.APP_NAME
        port:
          number: SERVICE_PORT
    retries:
      attempts: 5000
      perTryTimeout: 2s
      retryOn: connect-failure,internal,500,503,5xx,reset
    websocketUpgrade: true
  https:
  - timeout: 60s
    route:
    - destination:
        host: SERVICE_NAME.APP_NAME
        port:
          number: SERVICE_PORT
    retries:
      attempts: 5000
      perTryTimeout: 2s
      retryOn: connect-failure,internal,500,503,5xx,reset
    websocketUpgrade: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: SERVICE_NAME-BRANCH_NAME
  namespace: APP_NAME
spec:
  host: SERVICE_NAME.APP_NAME.svc.cluster.local
  subsets:
  - name: BRANCH_NAME
    labels:
      version: BRANCH_NAME