spring:
  application:
    name: fdadi-user-service
  datasource:
    #url: jdbc:mysql://fdadi-db:3306/fdadi?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:h2:mem:fdadi
    username: fdadi
    password: cL3ar#12
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
#server:
#  port: 8082

logging:
  level:
    com:
      clearavenue: DEBUG
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'