spring:
  application:
    name: fdadi-user-service
  datasource:
    url: jdbc:mysql://fdadi-db:3306/fdadi?useSSL=false&allowPublicKeyRetrieval=true
    username: fdadi
    password: cL3ar#12
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

logging:
  level:
    com:
      clearavenue: DEBUG
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/fdadi
    username: fdadi
    password: cL3ar#12
